// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzez3MJ8HGz3QpsWfj8kwJ0kuncmqSKQo',
    appId: '1:415579853261:web:7ab28f1ad755a8c7e3b484',
    messagingSenderId: '415579853261',
    projectId: 'library-app-7deed',
    authDomain: 'library-app-7deed.firebaseapp.com',
    storageBucket: 'library-app-7deed.firebasestorage.app',
    measurementId: 'G-2M7C9DLZC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD-aTpl08VYwESNgZ4oQTjCqttkEcxu14',
    appId: '1:415579853261:android:b95bb207eaedd7d8e3b484',
    messagingSenderId: '415579853261',
    projectId: 'library-app-7deed',
    storageBucket: 'library-app-7deed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd-XvS0RY7kOJgP3yfDtt9i0VZ2qmJkbY',
    appId: '1:415579853261:ios:a9750a26ab0bd414e3b484',
    messagingSenderId: '415579853261',
    projectId: 'library-app-7deed',
    storageBucket: 'library-app-7deed.firebasestorage.app',
    iosBundleId: 'com.example.libApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd-XvS0RY7kOJgP3yfDtt9i0VZ2qmJkbY',
    appId: '1:415579853261:ios:a9750a26ab0bd414e3b484',
    messagingSenderId: '415579853261',
    projectId: 'library-app-7deed',
    storageBucket: 'library-app-7deed.firebasestorage.app',
    iosBundleId: 'com.example.libApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzez3MJ8HGz3QpsWfj8kwJ0kuncmqSKQo',
    appId: '1:415579853261:web:5aa171eb4f4fa3d6e3b484',
    messagingSenderId: '415579853261',
    projectId: 'library-app-7deed',
    authDomain: 'library-app-7deed.firebaseapp.com',
    storageBucket: 'library-app-7deed.firebasestorage.app',
    measurementId: 'G-M1J2GCVHKW',
  );
}
