name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-14   # ✅ Use macOS 14 (Xcode 15.4 preinstalled)

    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode 15.4
        run: sudo xcode-select -switch /Applications/Xcode_15.4.app

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      # ✅ Clean & install fresh Pods (avoid cached broken FirebaseSharedSwift)
      - run: |
          cd ios
          pod deintegrate
          pod repo update
          pod install

      - run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
